version: '3.9'
services:
  postgres:
    build: ./postgres
    image: postgres:16
    environment:
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: hornetm3
      POSTGRES_DB: amur
    ports:
      - "5432:5432"
    