version: '3.9'
services:
  postgres:
    # build: ./postgres
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
     - ./data/postgis:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # command: cat amur3.sql | docker exec -i geogr_api-postgres-1 psql -U postgres
    
    