version: '3.9'
services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    hostname: postgres
    volumes:
     - ./postgres:/postgres
    ports:
      - "5432:5432"
    networks: 
    - net

  streamlit:
      build: ./streamlit
      ports:
        - '8501:8501'
      hostname: streamlit
      cap_add:
        - SYS_RESOURCE
      volumes:
        - ./streamlit:/streamlit
      networks:
        - net     

networks:
  net:
    driver: bridge